# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WtyczkaProjekt
                                 A QGIS plugin
 obliczanie pola i różnicy wysokości
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-11
        copyright            : (C) 2023 by E.S.,D.G.
        email                : 01169919@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WtyczkaProjekt class from file WtyczkaProjekt.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .projekt_2 import WtyczkaProjekt
    return WtyczkaProjekt(iface)
